# This MUST be a safe and secure key.
# It is recommended to only use alphanumeric characters and underscores.
# Use a website like https://www.random.org/strings/ to generate a secure key.
# Anyone who knows these keys will be able to bypass Mojang authentication.
allowed-keys:
  - ConfigureMe
